default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: postgres
  password: xtz7qr87
 
development:
  <<: *default
  database: onebittweet_development
 
test:
  <<: *default
  database: onebittweet_test
 
production:
  <<: *default
  database: onebittweet_production
  username: OneBitTwitter
  password: <%= ENV['ONEBITTWEETDATABASE_PASSWORD'] %>